### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#103]
# Features
## Comments API #28, #82 _in progress_
- [ ] Add relationship to `Project` - has many `Comments`
- [ ] Add relationship to `User` - has many `Comments`
## A `Project` has categories - in progress #105
- [ ] `ProjectCategories` API #33 , #105
- [ ] Add relationships to `Project` - has many `ProjectCategories` and `Categories`
- [ ] Add relationships to `Category` - has many `ProjectCategories` and `Projects`
## A `User` has categories
- [ ] `UserCategories` API #39 
- [ ] Add relationships to `User` - has many `UserCategories` and `Categories`
- [ ] Add relationships to `Category` - has many `UserCategories` and `Users`
## A `Skill` has categories
- [ ] `SkillCategories` API
- [ ] Add relationships to `Skill` - has many `SkillCategories` and `Categories`
- [ ] Add relationships to `Category` - has many `SkillCategories` and `Skills`
## A `Project` has roles
- [ ] `ProjectRoles` API #33 
- [ ] Add relationships to `Project` - has many `ProjectRoles` and `Roles`
- [ ] Add relationships to `Role` - has many `ProjectRoles` and `Projects`
## A `Project` has skills
- [ ] `ProjectSkills` API #33 
- [ ] Add relationships to `Project` - has many `ProjectSkills` and `Skills`
- [ ] Add relationships to `Skill` - has many `ProjectSkills` and `Projects`
## A `User` has skills
- [ ] `UserSkills` API #33 
- [ ] Add relationships to `User` - has many `UserSkills` and `Skills`
- [ ] Add relationships to `Skill` - has many `UserSkills` and `Users`
## A `User` has roles
- [ ] `UserRoles` API #33 
- [ ] Add relationships to `User` - has many `UserRoles` and `Roles`
- [ ] Add relationships to `Role` - has many `UserRoles` and `Users`
## Icons
- [ ] User icons #68, #100 
- [ ] Project icons
- [ ] Organization icons #69  
## Authorization
- [ ] Proper authorization across all endpoints - #59 among other issues
## Ember passthrough route
- [ ] Ember "passthrough" route
## Pagination
- [ ] Pagination to all endpoints that need it #85 
# Missing minor stuff on existing features
- [ ] **Category** slug should be unique. There is an index, but no `unique_constraint` in any of the changesets.
- [ ] **OrganizationMemberhship** missing ability to filter by role. This is currently an option for the "filter by organization slug" index endpoint on the rails api
- [ ] **OrganizationMembership** proper role and role change validation. 
- [ ] **Organization** has many memberships and members
- [ ] **Organization** name presence validation. Currently, only slug is validated. Since that one is auto-generated, makes more sense to have an error for name missing.
- [ ] **Post** state management - initially published, later edited
- [ ] **Post** status management - open, close
- [ ] **Post** type filtering (#86) as well as general type validation
- [ ] **Project** has many posts
- [ ] **RoleSkill** - missing the `cat` enum field. Do we still need that @JoshSmith ?
- [ ] **Skill** auto complete behavior - #60 among other issues
- [ ] **Skill** has many role skills and roles
- [ ] **User** has many memberships, organizations, posts, 
- [ ] **User** validations - uniqueness of email and username, etc.
- [ ] **User** onboarding process
# Minor features
- [ ] Obscenity validations
- [ ] Duplicate validation across all sluggable resources that clash
- [ ] Attachment validations (size, type, etc.)
# Issues
- [ ] `&Category.changeset/2` permits slug as a parameter. Don't think it matters because it gets overwritten by the `&ModelHelpers.generate_slug/2`, but could be removed
# Maintenance & refactoring
- [ ] Switch to using `ex_machina` factories
- [ ] **Something to consider:** Write an ex_machina strategy which would allow us simple building of JSON_API payloads for tests -https://github.com/thoughtbot/ex_machina#custom-strategies
# Low priority features
- post and comment images
- post likes
- mentions
- notifications
- user relationships (followers)

**Comment by joshsmith** [comment]
I am going to close this and fold it into #26 for a single point of coordination.
