### ISSUE TITLE
Introduce GithubComment model

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#1070]
# Problem

Similar to how we're doing with the `GithubIssue` model in #1067 , we need to do the same with a `GithubComment`model

## Subtasks
- [x] Add model and schema
- [x] Modify existing `CodeCorps.Comment` schema by introducing relationship and moving existing fields into IssueComment
- [x] Modify `Github.Adapters.Comment``
- [x] Modify parts of `GitHub.Event.IssueComment` namespace to deal with changes
  - Probably introduce `CommentLinker`
  - Modify `CommentSyncer`
  - Maybe modify `UserLinker`
- [x] Modify `CodeCorpsWeb.CommentController` endpoint paths to account for changes
  - Probably limited to `CodeCorps.Comment.Service`
