### ISSUE TITLE
Add ConversationController with show endpoint and policy

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#1287]
# Problem

I'm not 100% positive on this, but we likely need a `:show` endpoint in `ConversationController`

## Subtasks

- [ ] Implement `show?` policy
  - `current_user` is authorized if `conversation.user_id == current_user.id`
  - `current_user` is also authorized if `conversation.message.author_id == current_user.id`
  - `current_user` is also authorized if they are admin or higher on `conversation.message.project`
- [ ] write tests for policy
- [ ] Implement show endpoint in `ConversationController`
  - fetches by `id`
  - authorizes using policy
- [ ] write tests for controller
