### ISSUE TITLE
Perform switch from Postmark to SparkPost

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#1331]
# Problem

We want to change our email provider to SparkPost, since it better suits our needs.

## Subtasks
- [ ] Implement testing infrastructure
- [ ] Make the switch
- [ ] Create Issue: Optimize email sending to make use of sparkpost's multiple recipient support

## References

Might make #1330 obsolete or require it to be reworded
