### ISSUE TITLE
Send email when an invite is created

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#1361]
# Problem

When a user invite is created, we want to send an email to the specified email address.

The contents of the email differ slightly based on the invite being targeted at just getting a user created (no role or project id) or if it also has a project id and role specified.

Depending on how different the two emails potentially are, we may need to have separate templates for each of the two cases.

## Subtasks
- [ ] Add specifications on what the email content should be as a reply to this issue
  - it will likely contain a link to the ember app route which is used to claim the invite
- [ ] Add one or two models for the email, depending on specifications
- [ ] Blocked by #1351: Add a step to the invite claim transaction in `Accounts.UserInvites.claim_invite`, which builds and sends the email

## References

Partially blocked by #1350, #1351
