### ISSUE TITLE
Write tests for GitHub.Sync.installation_event/1

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#1373]
# Problem

`GitHub.Sync.installation_event/1` is currently completely untested. Since we want to unit test its individual elements to, it should suffice to test each possible outcome of the transaction performed by the tests, as defined by `GitHub.Sync.installation_event_outcome()`

## Subtasks
- [x] write tests for `{:ok, GithubAppInstallation.t()}` outcome
- [ ] write tests for `{:error, :validation_error_on_syncing_installation, Changeset.t()}` outcome
- [x] write tests for `{:error, :multiple_unprocessed_installations_found}` outcome
- [x] write tests for `{:error, :github_api_error_on_syncing_repos, struct}` outcome
- [ ] write tests for `{:error, :validation_error_on_deleting_removed_repos, {list, list}}` outcome
- [ ] write tests for `{:error, :validation_error_on_syncing_existing_repos, {list, list}}` outcome
- [ ] write tests for `{:error, :validation_error_on_marking_installation_processed, Changeset.t()}` outcome
- [ ] write tests for `{:error, :unexpected_transaction_outcome, any}` outcome

**Comment by zacck-zz** [comment]
Looks like the second clause is rather difficult to test as it is covered by other fail safes
