### ISSUE TITLE
Cannot Create new GitHub App

### ISSUE THREAD

**Issue by ghost** [code-corps/code-corps-api#1384]
# Problem

I am currently unable to register a new GitHub app for local development. 

Detail the problem here, including any possible solutions.

The form is not submitting, it appears due to errors in the Register new GitHub App form validation, specifically the Webhook URL. 

## Subtasks
- [x] Logged in to GitHub
- [x] Filled out GitHub App name field.
- [x] Filled out Homepage URL field.
- [x] Filled out User authorization callback URL field.
- [x] Filled out Webhook URL field.
- [x] Upon clicking 'Enter' form validation take me back to the Webhook URL field, even though there is a text entry within the input.

![image](https://user-images.githubusercontent.com/10345176/70749129-8c082580-1cf9-11ea-9239-8f209dec990e.png)

## References

Progress on: #
