### ISSUE TITLE
Write the API documentation for donations

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#245]
We should start out #10 by writing out how we expect our API to work by writing the documentation first. This should drive the other decisions that we make.

Anything in italics requires authorization.
- [x] DonationGoal - index, show, _create, edit, delete_ #381 
- [x] StripeAccount - _index, show_ #390 
- [x] StripeCard - _index, show_ #385 
- [x] StripeCustomer - _index, show_ #389 
- [x] StripePlan - index, show, _create_ #387 
- [x] StripeSubscription - _index, show, create, edit_ #391

**Comment by joshsmith** [comment]
We'll want to add an endpoint for `/projects/:id/stripe_button_url`, which is behind an authenticated route for the user who has permissions for it. This will return a `url` `string` for connecting to Stripe via OAuth. See #259.

**Comment by joshsmith** [comment]
We'll want a `/donation-goals` endpoint with `create`, `retrieve`, `update` and `delete`. These should only be possible to create by a project's organization's owner. See #374.

**Comment by begedin** [comment]
@JoshSmith 

> We'll want to add an endpoint for /projects/:id/stripe_button_url, which is behind an authenticated route for the user who has permissions for it. This will return a url string for connecting to Stripe via OAuth. See #259.

Are we sure we don't want to just add a `stripe_url` field to the project/organization instead?

**Comment by joshsmith** [comment]
@begedin I'm just worried about how long it would take to generate that JWT on every request. I think that could be a real performance issue since it involves crypto, which is why I suggested this.

**Comment by begedin** [comment]
Ah. Yeah, that makes sense. I assumed there's a reason.
