### ISSUE TITLE
Add models for donations

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#258]
- [x] `StripePlan` - plan for a connected account #367 - _in progress #383_
- [x] `StripeSubscription` - subscription for a connected account #361 - _in progress #383_
- [x] `DonationGoal` - fundraising goal for a project #374 - _in progress #378_
- [x] `StripeAccount` - describes standalone account on our platform #362 - _in progress #380_
- [x] `StripeCustomer` - customer for the platform (to be copied to the connect account) and customer for the standalone account #368 - _in progress #377_
- [x] `StripeCard` - card on a customer's account #363  - _in progress #377_

For #10.

**Comment by dmvt** [comment]
A few questions:

**Comment by joshsmith** [comment]
Looks like all done @begedin? Reopen if I'm wrong.
