### ISSUE TITLE
Migrate Rails API to Phoenix

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#26]
This is a journey issue that collects all the basic API endpoints to achieve parity with the soon-to-be deprecated Rails API.
## Minor features
- [x] **OrganizationMemberhship** missing ability to filter by role. This is currently an option for the "filter by organization slug" index endpoint on the rails api #132 _in progres_
- [x] **RoleSkill** - missing the `cat` enum field #129 
- [ ] Duplicate validation across all sluggable resources that clash
- [ ] Attachment validations (size, type, etc.)
## Issues
- [ ] **Skill** auto complete behavior - #60 among other issues
- [x] `&Category.changeset/2` should not permit slug as a parameter. #133
## Documentation
- [ ] Rewrite documentation to account for API changes
## Testing
- [ ] Auth view
- [ ] Changeset view
- [ ] Comment view
- [ ] Error helpers view
- [x] Organization membership view #124 _in progress_
- [x] Organization view #124 _in progress_
- [x] Post view _in progress_
- [ ] Preview view
- [ ] Project category view
- [x] Role skill view _in progress_
- [x] Role view _in progress_
- [x] Skill view _in progress_
- [ ] Slugged route view
## Maintenance & refactoring
- [ ] **Something to consider:** Write an ex_machina strategy which would allow us simple building of JSON_API payloads for tests -https://github.com/thoughtbot/ex_machina#custom-strategies
## Low priority features
- [ ] Find a way to test concurrency/possible race conditions for post numbering
- [ ] Obscenity validations
- post and comment images
- post likes
- mentions
- notifications
- user relationships (followers)
## Comments API #28, #82
- [x] Rename to `Comment` from `PostComment`
## A `User` has roles - _in progress_ #115
- [x] `UserRoles` API #40 
- [x] Add relationships to `User` - has many `UserRoles` and `Roles`
- [x] Add relationships to `Role` - has many `UserRoles` and `Users`
## A `Project` has categories - _in progress_ #105
- [x] `ProjectCategories` API #33 , #105
- [x] Add relationships to `Project` - has many `ProjectCategories` and `Categories`
- [x] Add relationships to `Category` - has many `ProjectCategories` and `Projects`
## A `User` has categories - _in progress_ #118
- [x] `UserCategories` API #39 
- [x] Add relationships to `User` - has many `UserCategories` and `Categories`
- [x] Add relationships to `Category` - has many `UserCategories` and `Users`
## A `User` has skills _in progress_
- [x] `UserSkills` API #33 
- [x] Add relationships to `User` - has many `UserSkills` and `Skills` #120 
## Endpoints
- [x] Add Categories API
- [x] Add Comments API _in progress_
- [x] Add Organizations API
- [x] Add Organization Memberships API
- [x] Add Project Categories API
- [x] Add Posts API _in progress_
- [x] Add Previews API
- [x] Add Projects API
- [x] Add Role Skills API
- [x] Add Roles API
- [x] Add Skills API
- [x] Add Slugged Routes API
- [x] Add User Categories API
- [x] Add User Skills API
- [x] Add Users API
## Icons
- [x] User icons #68, #100
- [x] Project icons #66
- [x] Organization icons #69 
## Critical maintenance
- [x] Switch to using `ex_machina` factories in all tests (i.e. replace `insert_` with factories) #138 
## Minor tasks
- [x] Add extra assertions to UserSkill controller test #81
- [x] **Category** slug should be unique. There is an index, but no `unique_constraint` in any of the changesets. #127 
- [x] **OrganizationMembership** proper role and role change validation. 
- [x] **Organization** has many memberships and members #124 
- [x] **Organization** name presence validation. Currently, only slug is validated. Since that one is auto-generated, makes more sense to have an error for name missing. #131
- [x] **Project** has many posts #130 _in progress_
- [x] **User** has many memberships, organizations #122 
- [x] **User** validations - uniqueness of email and username, etc. #128 
## A `Project` has skills _in progress_ #116
- [x] `ProjectSkills` API
- [x] Add relationships to `Project` - has many `ProjectSkills` and `Skills`
## A `Role` has skills #111 _in progress_
- [x] `SkillRoles` API 
- [x] Add relationships to `Skill` - has many `RoleSkills` and `Roles`
- [x] Add relationships to `Role` - has many `RoleSkills` and `Skills`
## Authorization
- [x] Proper authorization across all endpoints - #59 among other issues
- [x] Restrict certain endpoints to admin only
## Pagination
- [x] Pagination to all endpoints that need it #85
## Missing minor stuff on existing features
- [x] **Post** state management - initially published, later edited - #83, PR #168
- [x] **Post** status management - open, close (can use #160 for inspiration), #169, PR #168
- [x] **Post** type filtering (#86) as well as general type validation #163 _needs review_
- [x] **User** onboarding process
## Deployment
- [x] Test out migrating from existing Rails staging to a Phoenix staging server, along with db dump and import
- [x] Identify happy path for deployment in production
## Postgres
- [x] Identify differences btw Rails/Phoenix and plan migration #159 
## Bugfixes
- [x] Prevent email from rendering for anyone other than the currently authed user #194 _in progress #213_ 
- [x] Rewrite Post to filter on index as order_by created_at desc #202, _in progress #214_
- [x] Make find on slugs case-insensitive #203, _in progress #215_
- [x] Add limit to skills autocomplete query #205, _in progress #208_
## Ember
- [x] Finish adjusting for API differences https://github.com/code-corps/code-corps-ember/pull/363
- [x] Fix user-skills and user-categories to use user to fetch the appropriate data #204, _in progress #212_
- [x] Figure out new deployment strategy (S3 index via CloudFront?) https://github.com/code-corps/code-corps-ember/issues/375
## Analytics
- [x] Add analytics reporting to Segment #182 _in progress_

**Comment by joshsmith** [comment]
We should break out remaining tasks here into new issues and close this. It's stale.

**Comment by joshsmith** [comment]
Closing in favor of separate issues.
