### ISSUE TITLE
Refactor Controller Tests with helpers

### ISSUE THREAD

**Issue by mackenziehicks** [code-corps/code-corps-api#413]
# Problem

Refactor by adding helpers from api_case.ex to the tests for controllers.

See #404 as an example. 

## Subtasks
- [x]  User Role Controller Test #409 
- [x]  Project Skill Controller Test #408 
- [x]  User Category Controller Test #415 
- [x]  Role Skill Controller Test #414 
- [x]  Project Category Controller Test #418 
- [x] Organization Membership Controller Test #419 
- [x] User Skill Controller Test #421 
- [x]  Category #427 
- [x] Donation Goal #428 
- [x] Organization #430 
- [x] Preview #406  
- [x] Role #433
- [x] Skill #436 
- [x] Slugged Route #439 
- [x] Project #437 
- [x] Task #442 
- [x] User #443 
- [ ] Token
- [ ] Stripe Auth
