### ISSUE TITLE
Write policies for Stripe resources

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#447]
# Problem

We should write policies for all of our Stripe-related resources: accounts, cards, customers, plans, and subscriptions.

## Subtasks

1.  Look at existing policies to learn how they're written
2. Create issues for each of the policies we need to create

- [x] StripeConnectAccount #451 
- [ ] StripePlatformCard #454 
- [x] StripePlatformCustomer #453 
- [ ] StripeConnectPlan
- [ ] StripeConnectSubscription #457 

For each policy:

- [ ] Look at the blueprint to determine which actions you need to authorize on the resource
- [ ] Write out how you expect the policy to work inside its issue
- [ ] Write the policy tests
- [ ] Write the policy

## References

Progress on: #10

**Comment by joshsmith** [comment]
Closing in favor of actual issues.
