### ISSUE TITLE
Write Policy for Stripe Customer

### ISSUE THREAD

**Issue by amyschools** [code-corps/code-corps-api#453]
# Problem

This resource identifies a customer created on the [Stripe API](https://stripe.com/docs/api#customers).

Endpoints for this resource are `create` and  `show` for an individual Customer. A user must be authorized for both and they can only view or create their own record.

## Subtasks
- [ ] Stripe Customer factory - #455
- [ ] Stripe Customer policy for `show?` - #455
- [ ] Stripe Customer Policy tests for `show?` - #455
- [ ] Stripe Customer ability for `show?` - #455
- [ ] Stripe Customer policy for `create?`
- [ ] Stripe Customer Policy tests for `create?`
- [ ] Stripe Customer ability for `create?`

## References

Progress on: #447

**Comment by joshsmith** [comment]
Closed by #455.
