### ISSUE TITLE
Create an OrganizationInvite model

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#518]
# Problem

We need to have an `OrganizationInvite` model for inviting organizations.

## Subtasks
- [ ] Create a migration
- [ ] Generate a short, unique code that can be used to fulfill the invite
- [ ] Email for inviting the person
- [ ] Organization title for use in sending an invite email and pre-populating the create form when the invite is consumed
- [ ] A`fulfilled` boolean that can only move from `false` to `true`
- [ ] Index on the `code` and `email`
- [ ] Write unit tests

**Comment by snewcomer** [comment]
@JoshSmith looks like this is needed first?
