### ISSUE TITLE
Create a route, controller, and tests for organization invites

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#519]
# Problem

Once #518 is done, we'll need to create a route, controller, and tests for organization invites.

## Subtasks
- [x] Create the controller tests
- [x] Create the route
- [x] Create the controller (should only be a GET and PUT)

**Comment by vishaldeepak** [comment]
Shouldn't the controller have three routes?. Get, Put and `Create`?.  Wont we want an OrganizationInvite first be created through a controller action?

**Comment by begedin** [comment]
@vishaldeepak I would say that yes, `create` is also necessary, so approach your solution with that in mind. 

We should probably also support `index`, with the option to filter by coalesced ids. 

Look to other endpoints for examples on how to do that. `UserTaskController`, for example
