### ISSUE TITLE
Send an email when an OrganizationInvite is created

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#520]
# Problem

In #519 we'll want to kick off the sending of an email in a separate async process that sends to the `email` in the `OrganizationInvite` something along the lines of:

> Hi {{organization_title}},
>
> You've just been invited to add your first project on Code Corps.
>
> Click this link to get started: `the_url?code=CODE&organization_title=TITLE`

Clicking that link will take you to a page that verifies your organization invite and lets you create the new organization.

## Subtasks
- [ ] Create the email
- [ ] Test that the email contains the right information
- [ ] Hook the email up to be sent when an invite is created

**Comment by vishaldeepak** [comment]
Im picking this up. I'l be implementing it similar to `CodeCorps.Services.ForgotPasswordService`. When a new `organisation_invite` is created, send an email using `Mailer.deliver_later`

**Comment by vishaldeepak** [comment]
In the above example what should be `the_url` which when the user clicks redirects to code crops. Should I create a new `Get` route for organization creation or is it some route the ember app will take care off. I noticed that the `Get password reset` route is present in the ember app and the `Post password reset` route is present in corps api ember app(I think I am right).

**Comment by joshsmith** [comment]
I think we might want a router in the Ember app that then loads a specific record, with some `code` that gets created for the person to accept the invite. I'm not sure what the URL should be precisely. Probably something like `$ROOT_DOMAIN/invites/organization`?

**Comment by vishaldeepak** [comment]
I already have created `$ROOT_DOMAIN/organization/new` in the pull request #865. If a change is required let me know.
