### ISSUE TITLE
Add approved boolean to Project

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#521]
# Problem

We need to add an `approved` boolean value to projects that can only be set by a Code Corps admin.

## Subtasks
- [ ] Create the migration
- [ ] Write the model tests
- [ ] Create an approval changeset
- [ ] Write the controller tests
- [ ] Add filtering with the boolean to the index
- [ ] Write the view tests
- [ ] Add to the view
