### ISSUE TITLE
Update organization creation

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#522]
# Problem

An organization can be created by a user only if there is an `OrganizationInvite` that has not been `fulfilled` yet. That user must be set as the `owner` of the `Organization` via an `OrganizationMembership`.

We should also consider adding something like a `created_by_user_id` to both `Organization` and `Project` to track who originally created it.

## Subtasks
- [ ] Write migration
- [ ] Write model tests
- [ ] Update the changesets
- [ ] Update controller tests
- [ ] Update the controller logic

**Comment by snewcomer** [comment]
@JoshSmith want me to tackle this?

**Comment by joshsmith** [comment]
@snewcomer moving to low priority along with other tasks in this milestone.

**Comment by vishaldeepak** [comment]
HI, I am picking this up. This is my first contribution to the project, might take a little while.

**Comment by vishaldeepak** [comment]
Need a bit of clarification. Just want to know if I have the scenario right in my head

OrganizationInvite is a table that has
 - unqiue code.  --- What is this code supposed to be in programming terms.And how is it helpful?
 - email - the email address of the person to be invited
 - title - the title of the organisation.
 - fufiled - boolean field

And then who creates an organization invite?

The scenario in my head.
Code corps team(or some User?) wants to create a organisation. So they create an OrganisationInvite with an email-id and organisation title. The email is sent to this user. This user will get an email stating to create the organistion at Code-corps. From the email he is redirected to code-corps where  the user(he may not be signed in. In that case he must first be signed in) fills up a form that creates an Organisation. This user must be made head of the organisation through another class called OrganisationMembership. When the orgranisation is created the `fulfilled` field is set to true.

There already seem to be migrations for OrganisationMembership. Rolling back this migration does should do it`20170318082740_drop_organization_membership`.  

But perhaps creating a new migration is a better idea?

**Comment by vishaldeepak** [comment]
@JoshSmith It seems to me the requirement may be different than what has been specified above. One I can find out is `organization` already belongs to `belongs_to :owner, CodeCorps.User`. This is what I understand currently
 - Add function in `Policy.Organization` to accomadate for creation of organization via email.  If the user is not an admin but he has provided a code for a `unfulfilled` `OrganizationInvite`, he should be allowed to create
 - On creation the `OrganizationInvite` should be `fulfilled`
 - On creation update `created_by_user_id`
 - Remove `owner` relationship on `Organization` and instead use `OrganizationMembership` to track `User` to a `Organization`

**Comment by joshsmith** [comment]
This sounds generally right to me although I would like @begedin to share thoughts. I think we may want some of that behavior contained somewhere else.

**Comment by begedin** [comment]
The policy changes are tackled through a smaller issue - #1230

**Comment by begedin** [comment]
@joshsmith I'm not sure about removing owner. We've explicitly added it to simplify things. I'm not even sure we're planning for organization ownership transfer in the foreseeable future, so adding a `created_by_user_id` might be overthinking it at this point to.

The way I see it, the policy change via #1230 and auto-fulfilment via #1229 is enough to tackle this issue for now.

Once and if we want to make organizations transferable between users, we can add a simple migration to update `created_by_user_id` using `owner_id` and modify existing code further.

Anything else would be assuming too much right now, in my opinion.

**Comment by joshsmith** [comment]
Does this mean this is closeable now?

**Comment by joshsmith** [comment]
@begedin I'm assuming this can be closed. Let me know if I'm wrong.
