### ISSUE TITLE
Add approved boolean to Organizations

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#523]
# Problem

We need to add an `approved` boolean value to organizations that can only be set by a Code Corps admin.

## Subtasks
- [x] Create the migration
- [ ] Write the model tests
- [ ] Create an approval changeset
- [ ] Write the controller tests
- [ ] Add filtering with the boolean to the index
- [ ] Write the view tests
- [ ] Add to the view

**Comment by dleve123** [comment]
Going to try to tackle this!
