### ISSUE TITLE
Add bamboo for sending email

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#524]
# Problem

https://github.com/thoughtbot/bamboo

## Subtasks
- [ ] Add the bamboo library
- [ ] Set up configuration for sending emails
- [ ] Create a basic email and test it

**Comment by joshsmith** [comment]
Closed by #534.
