### ISSUE TITLE
Add tracking events to analytics for tracking donations

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#525]
# Problem

We should try to track the following, using the pattern of our Segment Analytics code in `lib`, the tracking we do in controllers, and the test tracking we do in tests.

## Subtasks
- [ ] When a user creates a Stripe Customer
- [x] When a user creates a platform card
- [ ] When a user creates a connect card
- [ ] When a user creates a subscription
- [x] When an organization creates a StripeConnectAccount
- [ ] When a project creates donation goals
- [ ] When a project donation goal is updated
- [ ] When a project donation goal is passed
- [ ] When a customer charge succeeds
- [ ] When a subscription is cancelled
- [ ] When a project activates donations
- [ ] When a card expires

Any others I can't think of off the top of my head right now.

**Comment by begedin** [comment]
An update on this:

Already handled

* stripe platform customer creation is tracked and tested
* stripe platform card creation is tracked and tested
* stripe connect account creation is tracked and tested

Not implemented, will be added in PR
* stripe connect subscription creation is tracked, but not tested
* donation goals create was neither tracked nor tested
* donation goals update was neither tracked nor tested

Difficult to implement in the current system

* connect customer creation - done during subscription creation, there is no `conn` in there to get the current user from.
* connect card creation - also part of subscription creation. no `conn`
* donation goal passed - very specific case
* When a customer charge succeeds
* When a subscription is cancelled
* When a project activates donations
* When a card expires

I'll look into getting these "difficult to track" cases to track properly
