### ISSUE TITLE
Events in webhooks need to be fetched from the Stripe API

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#550]
# Problem

We need to fetch events received by webhooks from the API before processing them in order to avoid possible replay attacks.

The only data that we should be capturing is the `id_from_stripe`, the `type`, and a `user_id` if it has it.

The `id_from_stripe`, along with the `user_id` (the Stripe Connect account's ID), should then be used to retrieve the Event from the API and proceed with any processing.

> When using Connect, you can also receive notifications of events that occur in connected accounts. For these events, there will be an additional user_id attribute in the received Event object.

Since we're making this change, we might as well fold in some other changes.

## Subtasks
- [x] Add `user_id` to `StripeEvent` (can be `null`)
- [x] Add `endpoint` to `StripeEvent` (`platform` or `connect`, not null, no default)
- [x] Attempt to insert the `id_from_stripe`, `type`, `user_id`, `endpoint`, and a `status` of `processing` into the database immediately, then kick off the async process and respond to Stripe, otherwise: do nothing
- [x] Fetch `Event` from Stripe's API before processing – do not pass any attributes collected from webhook, simply use the `id_from_stripe` and `user_id` (if needed) to fetch from Stripe

**Comment by joshsmith** [comment]
~This relies on us doing this first https://github.com/code-corps/stripity_stripe/issues/157~
