### ISSUE TITLE
Create schema for project task lists

### ISSUE THREAD

**Issue by green-arrow** [code-corps/code-corps-api#554]
# Problem

Currently, a project in code corps has many tasks. We need to create a new layer, 'task list', that allows ordered grouping of those tasks within a project. The task list should have the following properties:

* name: string
* position: integer
* tasks: has_many tasks
* project: belongs_to project

### project

* has_many: task lists

### task

* belongs_to: task list

## Subtasks
- [x] Create task list table and model
- [x] Modify project model to account for task lists
- [x] Modify task table and model to account for task list

**Comment by joshsmith** [comment]
@green-arrow maybe don't need to modify projects table but do need to add a has_many task lists.

**Comment by joshsmith** [comment]
Think we can leave off `description`, too for now.

**Comment by green-arrow** [comment]
@JoshSmith - Updated the original description

**Comment by WenInCode** [comment]
@JoshSmith @green-arrow I can create an issue for this on the ember side (I don't *think* there is one yet), and get started on it.

**Comment by joshsmith** [comment]
@WenInCode I don't believe there is anything yet. I think there are issues.

**Comment by joshsmith** [comment]
Closed by #557
