### ISSUE TITLE
Remove StripeAuth everywhere from the API

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#556]
# Problem

We need to remove the `StripeAuth` model and everything related to it.

We are creating Stripe managed accounts and no longer need OAuth to be able to connect to Stripe.

## Subtasks
- [x] Remove the StripeAuth model and tests (do not have a table to drop since it's virtual)
- [x] Remove from `web/models/abilities.ex`
- [x] Remove controller and tests
- [x] Remove from router
- [x] Remove view and tests
- [x] Remove reference to Stripe Auth from the API blueprint
- [x] Remove `CodeCorps.StripeTesting.Connect.OAuth`
- [x] Remove references to `Connect.OAuth` from `StripeConnectAccountService`
- [x] Remove anywhere that mentions the `stripe_redirect_uri` (including mention in USAGE.md)
