### ISSUE TITLE
RFC: When should the stripe account be created?

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#584]
# Problem

Right now, the API and the client are at adds with when the stripe connect account gets created.

The ember side does it as part of submitting funds recipient information. It takes all the filled out form fields, merges with the organization and the current user's email and posts that information to the API as a create action.

However, it seems the API assumes a create request will only contain a country code and an organization id. Also based on #572 (title, not the description), recipient info should be sent as part of an update request, **after** the account was already created. 

## Subtasks
- [x] Decide when the account should be created
- Initially, through a component that needs to be implemented. Existing create action is ok.
- [x] Redefine/move around some of the behaviors, based on that decision
- Nothing to redefine API side
- [x] Close this issue, create required issues to consolidate the client and the API
- Issue created ember side https://github.com/code-corps/code-corps-ember/issues/897

**Comment by begedin** [comment]
@JoshSmith Issues to be created: 

## Ember

* [x] Add the account creation component/step 
- https://github.com/code-corps/code-corps-ember/issues/897
- is shown if there is no stripe account 
- contains a country select dropdown, with US only 
- submitting creates the stripe connect account
- also need to switch the funds recipient action to do an update instead of a create
