### ISSUE TITLE
Move status logic from StripeAccountView into a separate module

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#599]
# Problem

The `StripeConnectAccountView` logic [here](https://github.com/code-corps/code-corps-api/blob/develop/web/views/stripe_connect_account_view.ex#L78-L165) can be moved into a separate module, with only the basic placeholder fields remaining in the view, to simplify things:

```Elixir

def recipient_status(record, _conn), do: AccountVerificationStatus.recipient(record)
def bank_account_status(record, _conn), do: AccountVerificationStatus.bank_account(record)
def personal_id_number_status(record, _conn), do: AccountVerificationStatus.personal_id_number(record)
def verification_document_status(record, _conn), do: AccountVerificationStatus.verification_document(record)

```
## Subtasks
- [ ] Move logic to separate module
- [ ] Add "delegation" methods to view
- [ ] Add tests for module, simplify tests for view

# Discussion

Where do we put the module? I'm thinking something like `lib/code_corps/presenters/account_verification_status.ex`.  Could use your thoughts, @joshsmith.

**Comment by arubis** [comment]
I'll be happy to hop on this when I've got an open block.

**Comment by joshsmith** [comment]
@arubis marking it as in-progress so you can take on it freely.
