### ISSUE TITLE
Add terms of use acceptance to connect account creation

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#602]
# Problem

We need changes in the API accommodating client changes for issue https://github.com/code-corps/code-corps-ember/issues/925

The create action should take `legal_entity_tos_acceptance_date`, combine it with `legal_entity_tos_acceptance_ip` and `legal_entity_tos_acceptance_user_agent`, which are extracted from `Plug.Conn{}`, then pass that into account creation

## Subtasks
- [ ] Extract IP address
- [ ] Extract user agent
- [ ] Merge with existing create attributes before passing into account service.

## References
https://github.com/code-corps/code-corps-ember/issues/925
