### ISSUE TITLE
Get rid of DateTime in StripeTesting

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#623]
# Problem

`stripity_stripe` has stopped using DateTime and instead now relies on integer unix timestamps only. Our `StripeTesting` module, located in various files under `lib/code_corps/stripe_testing` should also stop using `DateTime`.

This will also allow us to remove the method signature for `stringify_keys` from `MapUtils`.

## Subtasks
- [ ] Go through `lib/code_coprs/stripe_testing` and replace all instances of `DateTime.from_unix(integer_value)` to just plain `integer_value`
- [ ] Remove `defp stringify_keys(%DateTime{} = val), do: val` from lib/code_corps/map_utils
- [ ] Make sure tests still pass

**Comment by afsharalex** [comment]
Hi, 

Should I replace DateTime as `{:ok, date} = {:ok, integer_value}, or remove `:ok` 
Thanks.
