### ISSUE TITLE
Make TDD more test-driven by adding our linter and documentation

### ISSUE THREAD

**Issue by arubis** [code-corps/code-corps-api#644]
# Problem

`mix test.watch` allows you to add tasks beyond `test` to run. It would be helpful to also run our linter, `credo`. Because TDD is awesome.

## Subtasks
- [ ] Add `credo` to the tests run by `mix test.watch`; Cf. https://github.com/lpil/mix-test.watch
- [ ] Document use of `mix test.watch`
  - [ ] Include documentation of `--stale` flag, which `test.watch` can receive directly. See https://hexdocs.pm/mix/Mix.Tasks.Test.html#module-stale

**Comment by securingsincity** [comment]
@arubis I was looking at this issue, but I'm running into a slight issue. the `--stale` flag and `credo` do not play well together. Passing the `--stale` flag into `mix test.watch` results in the stale flag being passed to credo which causes the whole thing to die. 

Which of these options do you think make the most sense : 

1. Have `credo` but not support `--stale`
1. Don't have `credo` but document the use of `--stale`  
1. Force `--stale` by passing it into the configuration

```
if Mix.env == :dev do
  config :mix_test_watch,
    tasks: [
      "test --stale",
      "credo",
    ]
end
```

The problem with the third option is that you are forced to use `--stale` which might not be what you want.
