### ISSUE TITLE
Split up ignored event handler to target connect and platform events separately

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#645]
# Problem

At the moment, we have a list of events we specifically ignore, and a system which handles this list in `CodeCorps.StripeService.WebhookProcessing.IgnoredEventHandler`

This system incorrectly assumes the event type (ex. `account.updated`) is the only thing that effects our handling or ignoring of the event. The second factor we should take into account is if it's a platform or a connect event we are receiving.

This means that we need two ignored event handlers, one for platform events, the other for connect events, with separate lists for each.

Just as a basic example, "customer.updated" is handled for platform events, but should probably be ignored for connect events.

## Subtasks
- [ ] Rewrite the ignored events system so it works separately for connect and platform events
- [ ] Ignore "customer.updated" for connect events, but keep handling it for platform events.
- [ ] All of the currently ignored events should be ignored both on platform and connect webhooks
