### ISSUE TITLE
Feature Checklist: Matching users with projects

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#666]
# Problem

This issue should serve as a checklist and sub-issue aggregate for the feature of being able to match users with projects. The feature would be based on the idea of assigning skills to projects and users, then matching them based on those assignments.

To elaborate, project/organization owners and admins should be able to specify skills a certain project requires. 

Similarly, users should be able to specify skills they possess. 

This would enable us to match other users with projects and suggest projects for them to work on.

# What we need for assigning skills to projects

## Endpoints - All done

* [x] `POST /project-skills` to assign a skill to a project - creates record
* [x] `DELETE /project-skills` to remove a skill from a project - deletes record
* [x] `GET /project-skills` - to fetch all project skills (with coalesce support for `hasMany`)
* [x] `GET /project-skills/:id`

## Policies (Authorization) - All done

* [x] CREATE and DELETE should be admin or higher
* [x] SHOW and INDEX should be public

## Authentication - All done

* [x] CREATE and DELETE should require authentication
* [x] SHOW and INDEX should be public

# What we need for assigning skills to users

## Endpoints - All done

* [x] `POST /user-skills` to assign a skill to a project - creates record
* [x] `DELETE /user-skills` to remove a skill from a project - deletes record
* [x] `GET /user-skills` - to fetch all project skills (with coalesce support for `hasMany`)
* [x] `GET /user-skills/:id`

## Policies (Authorization) - All done

* [x] CREATE and DELETE should only be doable in the case of current user assigning or removing from themselves.
* [x] SHOW and INDEX should be public

## Authentication - All done

* [x] CREATE and DELETE should require authentication
* [x] SHOW and INDEX should be public

# Matching users with skills

For this part, I am not sure if we should be doing most of it on the API or the client. It's the whole "which side is smarter" debate. I'm leaning towards this being done on the API.

We would require a module, for example, `UserProjectMatcher` with a `&match_user/2`

```Elixir
defmodule CodeCorps.UserProjectMatcher do
  @default_project_count
  def match_user(%CodeCorps.User{} = user, project_count // @default_project_count) do
    get_list_of_projects_with_most_overlapping_skills(project_count) 
  end

  defp get_list_of_projects_with_most_overlapping_skills(amount) do
    # implementation goes here. probably a simple query initially
    # join user skills and project skills, group and count by project, order by count
    # limit the number of results to amount
  end
end
```

We would also require an endpoint which calls this module and returns the results. It would require authentication, but not authorization.

The ember side would need to have a service module which would access this endpoint. There are multiple ways we could likely achieve it, but that's something to discuss in the related ember issue.

* [ ] Create Task: Implement described `ProjectMatcher` module
* [ ] Create Task: Implement `GET /projects/for-user/:id` which calls module

**Comment by begedin** [comment]
@JoshSmith We should discuss here, before creating smaller issues to address each item listed here.

**Comment by JoshSmith** [comment]
@begedin what about actually assigning a user to a task?
