### ISSUE TITLE
Feature Checklist: Assigning users to tasks

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#667]
# Problem

This issue should serve as a checklist and sub-issue aggregate for the feature of being able to assign users to individual tasks. This feature would initially mostly mimic github's user assignment feature, but will likely get refined as we go along.

# What we need

## Models
- [x] `UserTask` model`
  - `user_id`, `task_id`, potentially `due_date`
  - `create_changeset` 
    - accepts `[:user_id, :task_id, :due_date]`
    - requires `[:user_id, :task_id]`
    -constrain uniqueness to user and task, so only one user can be assigned to a task. however, multiple tasks can be assigned to the same user.
  - `update_changeset`
    - accepts `[:due_date]`
    - requires nothing, so `:due_date` can be unset

## Endpoints

- [x] `GET /user-tasks` - index, should support coalescing for `hasMany`
- [x] `GET /user-tasks/:id` - show
- [x] `POST /user-tasks` - create endpoint
- [x] `PATCH /user-tasks/:id` - change due date
- [x] `DELETE /user-tasks/:id` - removes assignment

## Authentication

- [x] GET endpoints should be public
- [x] POST, PATCH and DELETE should be authenticated only

## Authorization (policies)

- [x] `[:show, :index]` should have none, everyone is able to do it
- [x] `[:create, :patch, :delete]` - All contributors can do this. We do not want to constrain the system too much. GitHub behaves similarly and it seems to work fine.

All of this is up for discussion, so feel free to add any suggestions

**Comment by joshsmith** [comment]
@begedin I think all contributors should be able to change assignment. I also am of the belief that we should only assign a single user to a task. If the task is large enough to need two people, that task should be broken down further.

**Comment by begedin** [comment]
I agree with the approach and have updated the description. 

Another question I just though of. The currently submitted designs make it seems like task assignment is sort of invite based. It even looks like the user can set a message when accepting it?

![image](https://cloud.githubusercontent.com/assets/1925540/22439582/81b38356-e730-11e6-9cd9-8bfc48f7b5fe.png)

Can we elaborate on that? Should the model be expanded to accommodate some/all of it?

**Comment by joshsmith** [comment]
@begedin the "I've got this!" thing is just a hover state. It shows your photo when hovering. I need to work on that UI because it's not ideal – makes it non-trivial to add someone else.

**Comment by begedin** [comment]
Only thing that's left here is the potential of having a `:due_date` for a task. I'll create a discussion issue for that part and close this.

**Comment by begedin** [comment]
Created #738, closing this.
