### ISSUE TITLE
Feature Checklist: Matching users with tasks

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#668]
# Problem

This issue should serve as a checklist and sub-issue aggregate for the feature of being able to match users with tasks. The feature would be based on the idea of assigning skills to tasks and users, then matching them based on those assignments.

To elaborate, task authors, as well as project/organization owners and admins should be able to specify skills a certain task requires. 

Similarly, users should be able to specify skills they possess. 

This would enable us to match other users with projects and suggest projects for them to work on.

# What we need for assigning skills to tasks - #670

## Models
* [x] `TaskSkill` model
  * `[:skill_id, :task_id]`
  * `create_changeset` - requires both fields. uniqueness on that specific combination of fields

## Endpoints
* [x] `POST /task-skills` to assign a skill to a project - creates record
* [x] `DELETE /task-skills` to remove a skill from a project - deletes record
* [x] `GET /task-skills` - to fetch all project skills (with coalesce support for `hasMany`)
* [x] `GET /task-skills/:id`

## Policies (Authorization)

* [x] CREATE and DELETE should be task author, project admin or higher. **Up for discussion**. Possibly just a `contributor` might be enough.
* [x] SHOW and INDEX should be public

## Authentication

* [x] CREATE and DELETE should require authentication
* [x] SHOW and INDEX should be public

# What we need for assigning skills to users

## Endpoints - All done

* [x] `POST /user-skills` to assign a skill to a project - creates record
* [x] `DELETE /user-skills` to remove a skill from a project - deletes record
* [x] `GET /user-skills` - to fetch all project skills (with coalesce support for `hasMany`)
* [x] `GET /user-skills/:id`

## Policies (Authorization) - All done

* [x] CREATE and DELETE should only be doable in the case of current user assigning or removing from themselves.
* [x] SHOW and INDEX should be public

## Authentication - All done

* [x] CREATE and DELETE should require authentication
* [x] SHOW and INDEX should be public

# Matching users with tasks

For this part, I am not sure if we should be doing most of it on the API or the client. It's the whole "which side is smarter" debate. I'm leaning towards this being done on the API.

We would require a module, for example, `UserTaskMatcher` with a `&match_user/2`

```Elixir
defmodule CodeCorps.UserTaskMatcher do
  @default_task_count
  def match_user(%CodeCorps.User{} = user, task_count // @default_task_count) do
    get_list_of_tasks_with_most_overlapping_skills(tasks_count) 
  end

  defp get_list_of_tasks_with_most_overlapping_skills(amount) do
    # implementation goes here. probably a simple query initially
    # join user skills and tasks skills, group and count by task, order by count
    # limit the number of results to amount
  end
end
```

We would also require an endpoint which calls this module and returns the results. It would require authentication, but not authorization.

The ember side would need to have a service module which would access this endpoint. There are multiple ways we could likely achieve it, but that's something to discuss in the related ember issue.

* [x] Create Task: Implement described `TaskMatcher` module
* [x] Create Task: Implement `GET /tasks/for-user/:id` which calls module

**Comment by joshsmith** [comment]
@begedin don't we have `ProjectSkill` right now?

**Comment by joshsmith** [comment]
Or is that supposed to be task skills?

**Comment by begedin** [comment]
@JoshSmith Sorry, yes. The issue is similar in writing to #666, so I did a copy paste and missed a few cases.

**Comment by begedin** [comment]
Closing this, since the last few items on the checklist have separate issues and are part of the related project.
