### ISSUE TITLE
Add events API

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#687]
# Problem

We want to be able to add events, so that people can list things like conferences, meetups and hackathons on Code Corps.

## Subtasks
- [ ] Add postgis extension (dev + Heroku + docs)
- [ ] Add events table, w `title`, `description`, `time` (UI will have date picker and time picker to represent one timestamp), `location` (may need expanded into more specific information like lat/lng), `
- [ ] Add `events_skills` table (many-to-many)
- [ ] Add `users_events` table (many-to-many), w/ column `rsvp` of `yes`, `maybe`, `no`, and `host` boolean
- [ ] Add `organizations_events` table (many-to-many)
- [ ] Automatically add `host` for event upon event creation
- [ ] Add controllers for each model
- [ ] Write controller tests
- [ ] Send email when RSVPing
- [ ] Send reminder email
- [ ] Add event search functionality using Postgis using a zip code and a radius (https://github.com/bryanjos/geo)
- [ ] Event can be canceled or modified
- [ ] Modifying or canceling an event sends an email to the attendees
