### ISSUE TITLE
Migrate to project users from organization memberships

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#708]
# Problem

- [x] Make a user an owner of an organization directly #709 
- [x] Make a user an owner of a project directly #710 
- [x] Create project memberships #711 
- [x] Migrate existing organization memberships over to project memberships #712 
- [x] Migrate existing organization owners over to the new direct organization owner and project owner #714 #715 
- [x] Add project user controllers and tests #713 
- [x] Check permissions for orgs against organization owners #716 
- [x] Check permissions against project memberships #717 
- [x] Remove organization memberships #718

**Comment by joshsmith** [comment]
@begedin can this be closed?

**Comment by begedin** [comment]
I believe so. The last two issues have been closed to.
