### ISSUE TITLE
Once password reset is done, send a notification email to the user

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#732]
# Problem

This is just additional security that a lot of sites have.

Once the user successfully resets their password, they will be sent an email notifying them of this process being done, with a link to request another reset in case "someone else did this".

The email should contain something like:

**Subject**: Your password on codecorps.org has been reset

Your password on [codecorps.org](www.codecorps.org) has been reset. 

If you did not do this, please click [here]() (password reset link) to reset it again.

If this was done by you, then feel free to ignore this email.

## Subtasks
- [ ] on successful password reset (when the endpoint in #731 returns an OK), generate and send the email above
- [ ] add tests to ensure this happens
- [ ] test the email as well

@JoshSmith I would like to stress that this is purely optional and not something that should in any way be considered a prerequisite to label #498 as complete, but it is something that some sites do, so I wanted to have an issue for it.

## References

Progress on: #498
