### ISSUE TITLE
Implement task matcher endpoint

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#737]
# Problem

In addition to #736, we would require an endpoint which calls the described module and returns the results. It would require authentication, but not authorization.

The ember side would need to have a service module which would access this endpoint. There are multiple ways we could likely achieve it, but that's something to discuss in the related ember issue.

## Subtasks

- [ ] Add described endpoint - endpoint should receive a user id and return a list of matched tasks. It can probably go into `/tasks/for-user/
- [ ] Endpoint should require authentication, but it's safe enough not to require any authorization
- [ ] Add tests for endpoint

# References

- related to #668, #736
- blocked by #736
