### ISSUE TITLE
Send GitHub updates when a Code Corps project is updated

### ISSUE THREAD

**Issue by npendery** [code-corps/code-corps-api#787]
# Need to update GitHub repo when the corresponding CC project's tasks are updated.

This is partially blocked until we get the first steps of the GitHub integration done from [Milestone 11](https://github.com/code-corps/code-corps-api/milestone/11). It ca

We need to update Github module `lib/code-corps/github.ex` to include functions for each of the subtasks below.

## Subtasks for each action needed
- [ ]  Create task
- [ ]  Update task
- [ ]  Delete task
- [ ]  Create task comment
- [ ]  Update task comment
- [ ]  Delete task comment

**Comment by begedin** [comment]
Closing this in favor of #800, #801, #802, #803, #804 

This issue is a bit too broad and the smaller, individual issues should be more suitable for contributors. The smaller issues cover create/update behavior on tasks and comments. There is no feature to delete tasks or comments right now, so there is nothing to sync with github in those cases.
