### ISSUE TITLE
Add ability to associate user with github account

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#791]
# Problem

In order to connect a user account, we need to be able to associate a codecorps user with github user information.

## Solution

We need to write a function which handles this. It can be defined under `CodeCorps.GitHub.associate/2` where the first parameter is a `CodeCorps.User`, while the second is a `Tentacat.response`, or more simply, a map, containing an `id`, which is a github user id, among other things.

To perform the actual association, the simplest initial approach is to have a `github_id` field on the user. We also need a changeset which performs the association.

## Subtasks
- [ ] add `github_id` string field to user
- [ ] add `github_associate_changeset` to user, which casts and requires this field
- [ ] add test for the changeset
- [ ] add `CodeCorps.GitHub.associate/2`, which retrieves a user and a params map, calls the changeset, then updates user and returns the outcome (`{:ok, user}`, or `{:error, changeset}`)
- [ ] add tests for the function, one for each outcome.

**Comment by securingsincity** [comment]
I can take this one.

**Comment by begedin** [comment]
So you did, and you did nicely. 👍
