### ISSUE TITLE
Add Github ID fields for all related models

### ISSUE THREAD

**Issue by npendery** [code-corps/code-corps-api#798]
# Problem

Need to add a `github_id` field for any model that will be connected to a related github model

## Subtasks
- [x] Add user field (covered in #792)
- [x] Add task field
- [x] Add project field
- [x] Add comment field

Progress on: # Milestone 11

**Comment by securingsincity** [comment]
I can take this one since I already took care of #792

**Comment by npendery** [comment]
Thanks for the offer @securingsincity, but already started on it, should have a PR up in a sec!

**Comment by securingsincity** [comment]
ok cool.
