### ISSUE TITLE
When posting comment on cc, if task is tied to github issue, also create github comment

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#801]
# Problem

A CodeCorps project might be connected to a github repository. In such a project, all Tasks should also be connected to a GitHub issue.

When a comment is created for such a task, a comment should also be created on github for the related issue.

We should also extract the comment update behavior into a module, since it's getting more complex now.

## Subtasks
- [ ] If the module does not yet exist, add `/lib/codecorps/task/comment.ex`, namespaced `CodeCorps.Task.Comment`
- [ ] Add a `create` function to the module. Iit should accept the current user and an attributes map
  - creates comment
  - if the associated `Task` is related to a `GithubRepo`, use information from the task (`GithubRepo`, `github_issue_number`, to create a github issue comment on github
   - this should be done on behalf of the comment user, or, if the comment user is not connected with github, on behalf of the identity provided in #800
- [ ] Modify Comment controller update action to call this new module
- [ ] Write tests for new module update function to ensure the github sync part works. The controller action itself is already tested well enough.

**Comment by joshsmith** [comment]
Closed by #925.
