### ISSUE TITLE
Add OrganizationGithubAppInstallation

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#842]
# Problem

We need to add an `OrganizationGithubAppInstallation` and allow for simultaneous creation of this _and_ the `GithubAppInstallation` when creating on that API endpoint.

## Subtasks
- [x] Add an `OrganizationGithubAppInstallation` and tests
- [x] Add policy and policy test
- [x] Add view and view test
- [x] Add `index`, `show`, `create`, and `delete` endpoints and tests
- [ ] Add relationship of the requesting organization to the `GithubAppInstallation`
- [ ] Allow for simultaneous creation of the `OrganizationGithubAppInstallation` _and_ the `GithubAppInstallation` when creating on that API endpoint

**Comment by begedin** [comment]
I posted a question in the associated https://github.com/code-corps/code-corps-api/pull/843#pullrequestreview-48838473, pasting here:

> I'm not completely clear why we need a many-to-many between an app installation and an organization. Could you clear that up for me a bit?

Also, from the issue description (sorry, doing notifications in order), it seems like the `GithubAppInstallation` gets 2 relationships (and implicitly a 3rd) through this issue:

```Elixir
belongs_to :requesting_organization
has_many :organization_github_app_installation
has_many :organizations, through: :organization_github_app_installation
```

Is that correct?

**Comment by joshsmith** [comment]
That is correct.

The reason we need the app installation and organization to be many-to-many should be apparent from the UI if you imagine connecting an existing installation the user has available to them to another organization. You could have `Org A` and `Org B` both connected to `Installation A` and Installation B`, and `Org B` connected to `Installation B` and `Installation C`.
