### ISSUE TITLE
Remove ja_resource

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#864]
# Problem

`ja_resource` has been giving us trouble before and will likely continue to give us more trouble.

Our initial reasoning for introducing it to our project was to reduce our controller boiler plate. However, with the way our other tools developed, this benefit has been gradually reducing and we now barely have any less boilerplate than before, and the cost has been reduced readability of code, as well as performance, in some cases.

- we have to override several hooks per controller, due to using custom, non-basic behavior
- it clashes heavily with our authorization layer, in some places causing us to load the same resource twice, before authorizing and performing the action
- it makes it hard to switch to a "better" authorization framework. We've been discussing switching away from canary in the past and `ja_resource` was the main blocker in doing so.
- the switch to Phoenix 1.3 means several things that further reduce the usefulness of `ja_resource`
  - our controllers are now in the `CodeCorpsWeb` namespace, while models are in `CodeCorps`, so each controller needs to override the `ja_resource` `model/0` function to get it working
  - the aim is to move away from the model concept and into contexts and `ja_resource` depends heavily on the model concept to generally work
  - with the introduction of `FallbackController` and action fallbacks, we can reduce boilerplate that way
- the library itself is not updated often, so we're bound to encounter more issues as time goes on

# Conclusion

With all that in mind, my recommendation is to get rid of `ja_resource` completely. This would involve...

# Requirements

- rewriting our controller code to the old action system
- make use of fallback actions and `FallbackController` to reduce the boilerplate that way
- make use of our own, custom plugs to reduce boilerplate further
- slight adjustment of our authorization plugs

# Notes

The advantages are

- less issues down the line
- increased flexibility
- improved code clarity and explicitness

*On a personal note*, it's my opinion that we introduced `ja_resource` early in our elixir experience when we still tried to make it work sort of like ruby. Now that I have more experience with the language and the phoenix framework, the negatives, to me, seem to outweigh the positives.

With a simple REST api, it might still work, but with the things we do here, I don't think it does.

**Comment by begedin** [comment]
To add, we can do this gradually. Switch one or two major controllers to it as examples, then volunteers can take it over bit by bit. Once everything is switched, we remove the package from our dependencies.

**Comment by snewcomer** [comment]
I'd be interested in helping out here.

**Comment by begedin** [comment]
@snewcomer This is still at a "suggestion" level, but if we go through with it, your help is much appreciated.

**Comment by joshsmith** [comment]
I agree with this move and think it actually decreases the potential overhead for contributors, which is always a plus in my book.

**Comment by joshsmith** [comment]
Can we make some smaller issues to go after this, and @snewcomer would you be interested now in tackling some of those?

**Comment by snewcomer** [comment]
@JoshSmith yep I am available to help with this.

**Comment by joshsmith** [comment]
@begedin if you have some time to break this down the way you'd like to see it, let me know.

**Comment by begedin** [comment]
@JoshSmith I'd have to figure out how to do it first, using an example of a single controller. There's a lot of coupling going on under the hood at the moment, with our authorization being implemented around ja_resource. I'd have to take a look and try at least a small example first.

I'll see what I can do.

**Comment by begedin** [comment]
@JoshSmith It was difficult to grasp by just looking, so I went ahead and submitted a PR using the example of the comment controller - #867

Some notes on it

- Controllers that use `ja_resource` do not make it perfectly clear which actions are "enabled" for the controller and which are not
- The change increases the amount of code per controller slightly, but the benefit is performance, and readability, IMO
- An action at a time can be switched over, if switching the whole controller in a single PR is too large a change

**Comment by begedin** [comment]
#867 deals with switching one controller away. Using the knowledge gained from there, here's the full procedure on how to switch

# Procedure

- pick a controller to switch
- view actions this controller should support in `lib/code_corps_web/router.ex`
- add `action_fallback CodeCorpsWeb.FallbackController`. This makes it so in case a with clause within the controller action fails, a sort of "catch all" function will be called from `FallbackController`
- add `plug CodeCorpsWeb.Plug.DataToAttributes`. This converts the `data` hash within the conn params from the json api structure into a flat map convenient for usage with changesets
- for each action
   - remove that action from any `load_resource`, `load_and_authorize_resource`, etc. plugs in that controller
   - remove any `def handle_#{action}` functions
   - write a `def #{action}(conn, params) do`. For the standard `create`, `update` `delete`, `show` and index actions. See examples below on how these functions should be written, usually
   - rewrite the policy function for that action to support params instead of a changeset if necessary. See section below for pointers.

That should be the whole procedure. We already have controller tests in place, so if the process has been done correctly, the tests should pass.

Some additional steps might be necessary, however, if there are some specifics to an action. For those, we will be here to provide feedback.

## How to rewrite controller actions

```Elixir
@spec index(Conn.t, map) :: Conn.t
def index(%Conn{} = conn, %{} = params) do
  with resources <- ResourceModule |> Query.id_filter(params) |> Repo.all do
    conn |> render("index.json-api", data: resources)
  end
end

@spec show(Conn.t, map) :: Conn.t
def show(%Conn{} = conn, %{"id" => id}) do
  with %ResourceModule{} = resource <- ResourceModule |> Repo.get(id) do
    conn |> render("show.json-api", data: resource)
  end
end

@spec create(Plug.Conn.t, map) :: Conn.t
def create(%Conn{} = conn, %{} = params) do
  with %User{} = current_user <- conn |> Guardian.Plug.current_resource,
       {:ok, :authorized} <- current_user |> Policy.authorize(:create, params),
       {:ok, %Comment{} = resource} <- %ResourceModule{} |> ResourceModule.create_changeset(params) |> Repo.insert do
    conn |> put_status(:created) |> render("show.json-api", data: resource)
  end
end

@spec update(Conn.t, map) :: Conn.t
def update(%Conn{} = conn, %{"id" => id} = params) do
  with %ResourceModule{} = resource <- ResourceModule |> Repo.get(id),
       %User{} = current_user <- conn |> Guardian.Plug.current_resource,
       {:ok, :authorized} <- current_user |> Policy.authorize(:update, resource),
       {:ok, %ResourceModule{} = resource} <- resource |> ResourceModule.changeset(params) |> Repo.update do
    conn |> render("show.json-api", data: resource)
  end
end
```

So to recap, the actions work like

### `index` action

- apply filters from query params to load data
- render data

### `show` action

- load resource
- render resource

### `create` action

- authorize action for current user and parameters (requires rewriting that policy to use a params map instead of a changeset, expect `{:ok, :authorized}`
- perform insert action
- render resulting resource

### `update` and `delete` actions

- load resource
- authorize action for current user on resource, expect `{:ok, :authorized}`
- perform update/delete
- render resource, or no content for delete

### Examples in code

-`CodeCorpsWeb.CommentController` has examples for standard `index`, `show`, `create` and `update` actions


## How to rewrite policies

This consists of several relatively simple steps.

- For each action being switch away, we need to move the `def can` function clause out of the `defimpl` block in `policy.ex` into the root namespace of the `CodeCorps.Policy` module. 
- We also need to make the clause private instead of public.

- If any of the clauses expect a changeset, they should now expect a simple map of params:

```Elixir
defp can?(%User{} = user, :some_action, %Changeset{data: %Resource{}} = changeset), do: Policy.Resource.some_action?(user, changeset)
```

becomes

```Elixir
defp can?(%User{} = user, :some_action, %{} = params), do: Policy.Resource.some_action?(user, params)
```

- in this case, the policy module itself also need to be rewritten to support a params map. Since in most cases, these policies simply look at the `changeset.changes` map, the rewrite ought to be simpler. If there is trouble, someone will be available to provide pointers.

### Examples in code

- the rewrite has been done for `Policy.Comment.create?`

**Comment by begedin** [comment]
# ToDo List

## Phase 1

- [x] Switch `CategoryController` away from `ja_resource` and `canary` - in progress by @crodriguez1a in #881 
- [x] Switch `CommentController` away from `ja_resource` and `canary`
- [x] Switch `DonationGoalController` away from `ja_resource` and `canary` - #889 
- [x] Switch `GithubAppInstallationController` away from `ja_resource` and `canary` - #890 
- [x] Switch `GithubRepoController` away from `ja_resource` and `canary` - #891
- [x] Switch `OrganizationController` away from `ja_resource` and `canary` - #892
- [x] Switch `OrganizationGithubAppInstallationController` away from `ja_resource` and `canary` - #893
- [x] Switch `OrganizationInviteController` away from `ja_resource` and `canary` - #894
- [x] Switch `PreviewController` away from `ja_resource` and `canary` - #895
- [x] Switch `ProjectController` away from `ja_resource` and `canary` - #896
- [x] Switch `ProjectCategoryController` away from `ja_resource` and `canary` - #897
- [x] Switch `ProjectGithubRepoController` away from `ja_resource` and `canary` - #898
- [x] Switch `ProjectSkillController` away from `ja_resource` and `canary` - #899
- [x] Switch `ProjectUserController` away from `ja_resource` and `canary` - #900
- [x] Switch `RoleController` away from `ja_resource` and `canary` - #901
- [x] Switch `RoleSkillController` away from `ja_resource` and `canary` - #902
- [x] Switch `SkillController` away from `ja_resource` and `canary` - #903
- [x] Switch `SluggedRouteController` away from `ja_resource` and `canary` - #904
- [x] Switch `StripeConnectAccountController` away from `ja_resource` and `canary` - #905
- [x] Switch `StripeConnectPlanController` away from `ja_resource` and `canary` - #906
- [x] Switch `StripeConnectSubscriptionController` away from `ja_resource` and `canary` - #907
- [x] Switch `StripePlatformCardController` away from `ja_resource` and `canary` - #908
- [x] Switch `StripePlatformCustomerController` away from `ja_resource` and `canary` - #909
- [x] Switch `TaskController` away from `ja_resource` and `canary` (in progress, #805) - #911
- [x] Switch `TaskListController` away from `ja_resource` and `canary` - #910
- [x] Switch `TaskSkillController` away from `ja_resource` and `canary` - #912
- [x] Switch `UserController` away from `ja_resource` and `canary` - in progress by @snewcomer  in #882, - #913
- [x] Switch `UserCategoryController` away from `ja_resource` and `canary` - #914
- [x] Switch `UserRoleController` away from `ja_resource` and `canary` - #915
- [x] Switch `UserSkillController` away from `ja_resource` and `canary` - #916
- [x] Switch `UserTaskController` away from `ja_resource` and `canary` - #917

## Phase 2

- [x] Remove `ja_resource` as a dependency
- [x] In any remaining controllers, cleanup any ja_resource callbacks. Removing the dependency should cause warnings to appear so this should be easy
- [x] Remove `canary` as a dependency
- [x] Remove `helpers/authentication_helpers.ex`. It should no longer be necessary with `canary` gone. 
- Remove `action_fallback CodeCorpsWeb.FallbackController` from all controllers and instead move it into the `CodeCorpsWeb` module into the `def controller` `quote` block
- Remove `plug CodeCorpsWeb.Plug.DataToAttributes` from all controllers and move it into `router.ex` into the `:api` pipeline.
- Remove `plug CodeCorpsWeb.Plug.IdsToIntegers` from all controllers and move it into `router.ex` into the `:api` pipeline.

**Comment by joshsmith** [comment]
@snewcomer thanks to @begedin there are some real specifics here for how to tackle working on this.

**Comment by snewcomer** [comment]
Awesome!  Will be tacking a few tomorrow with a coworker here!

**Comment by vishaldeepak** [comment]
If available, id like to contribute on 1 or 2 controllers myself. Perhaps `project_controller` and `preview_controller`

**Comment by begedin** [comment]
@vishaldeepak, @snewcomer Feel free to do so.

Also feel free to create individual issues for those parts you would like to tackle. As long as the body of the issue contains `Progress on #864`, I will update the text here to mark those items as taken.

**Comment by begedin** [comment]
I have now created separate issues for each task in phase one. Feel free to visit individual issues and assign yourselves if you wish to tackle any of them. If you are unable to assign, label as in progress and comment taking it, so someone else can assign you.

I will create phase 2 issues once phase 1 is complete

**Comment by begedin** [comment]
I've moved the remaining parts of phase 2 tasks into #1069
